language: node_js
node_js:
  - 4
  - 5
  - 6
git:
  depth: 3

sudo: false

before_install:
  - export CHROME_BIN=chromium-browser  # Karma CI
  - export DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c webdriver-manager start 2>&1 &  # Protractor CI
  - sleep 1  # give server time to start

branches:
  only: master

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=9b18c72997769f3867ef2ec470e626d39661795d

cache:
  directories: node_modules

deploy:
  provider: heroku
  api_key:
    secure: DcnDdBXbOXGwBxkniDh/BBQZigyb5pmIpVWjRsqIs7D2MGBCJSa9mLS0l/q8F2UK4Rl$
  app: guarded-escarpment-97496
